db:
  image: postgres

# rabbitmq:
#     image: rabbitmq

b4c:
  image: lalu/b4c
  command: crossbar start
  # command: python manage.py runserver 0.0.0.0:8080
  volumes:
    - .:/app
  ports:
    - "8080:8080"
  links:
    - db
    # - rabbitmq

